---
abstract: "\"factory reset\" for a Moose class"
author:
  - 'Aaron Cohen <aarondcohen@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker::CPANfile: 0.05
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Role-Defaultable
no_index:
  directory:
    - t
    - inc
requires:
  ExtUtils::MakeMaker: 0
  ExtUtils::MakeMaker::CPANfile: 0
  Moose: 0
  Sub::IsEqual: 0
  Test::Most: 0
  namespace::autoclean: 0
resources:
  bugtracker: http://github.com/aarondcohen/perl-moosex-role-defaultable/issues
  homepage: http://github.com/aarondcohen/perl-moosex-role-defaultable
  repository: git://github.com/aarondcohen/perl-moosex-role-defaultable.git
version: 1.01
